### ISSUE TITLE
Xamarin.Forms UWP app - 'response' does not exist error after upgrade to 2.2.9

### ISSUE THREAD

**Issue by faceoffers28** [Redth/ZXing.Net.Mobile#563]
After upgrading from 2.1.44 to 2.2.9, I'm getting the following error when trying to scan.

error CS0103: The name 'response' does not exist in the current context

When the error hits, it pulls up this method in the App.g.i.cs file.

```
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif

```
I'm running this version of the Xamarin SDKs. https://releases.xamarin.com/stable-release-cycle-9/

My app is a PCL targeting 259. I'm running Xamarin.Forms 2.3.4.231. I'm using the ZXingScannerView.

Any help is much appreciated. Thanks!

**Comment by faceoffers28** [comment]
By the way, when I'm debugging the page, this line in the OnAppearing method is what triggers the error. zxing.IsScanning = true;. If I comment out this line, the page appears, the overlay displays, but the camera does not display, so scanning does not occur.

**Comment by faceoffers28** [comment]
Here is more information on the UnhandledException. "The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)". "Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference
Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)". I downgraded to Xamarin.Forms 2.3.3.193 (same version that is used in the source), but the issue still persists. This might be an issue with the Microsoft.NETCore.UniversalWindowsPlatform package. I'm running this version 5.1.0.

**Comment by faceoffers28** [comment]
Updating to this version of the Microsoft.NetCore.UniversalWindowsPlatform fixed the issue. This is the last version that will work with Visual Studio 2015 Update 3 or later.  https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.2.3 I was running version 5.1.0.

**Comment by anujpotdar** [comment]
faceoffers28 solution worked for me. Thank you.
